# Generated by Django 5.0.3 on 2026-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claimed_video_rewards',
            field=models.ManyToManyField(blank=True, related_name='rewarded_profiles', to='core.course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='money_price',
            field=models.IntegerField(default=0),
        ),
    ]
